export  { default as Header} from './Header/Header';
export  { default as Footer} from './Footer/Footer';
export  { default as NotFound} from './NotFound/NotFound';
export  { default as Search} from './Search/Search';
export  { default as Spinner} from './Spinner/Spinner';
export  { default as Post} from './Post/Post';
export  { default as PostGallery} from './PostGallery/PostGallery';
export  { default as Pagination} from './Pagination/Pagination';
export  { default as Privacy} from './Privacy/Privacy';